### ISSUE TITLE
Content pack installing error

### ISSUE THREAD

**Issue by Bijay2052** [shrunbr/graylog_pfsense_barnyard2#1]
I have configured graylog with input where pfsense is sending logs. And i am sending snort alret logs with systemlogs to input in graylog.
My graylog server version is Graylog v3.2.5+b0d3334. But i get following error while installing your content pack.
Could you please help with it. I have stumbled upon many tutorial but i am unable to parse snort logs.
Error
Installing content pack failed with status: Error: cannot POST http://192.168.99.152:9100/api/system/content_packs/84e6fc57-9d52-407d-aad9-707a58ef9a89/1/installations (500). Could not install content pack with ID: 84e6fc57-9d52-407d-aad9-707a58ef9a89

**Comment by shrunbr** [comment]
Try upgrading to 3.3.X and see if it works, if it doesn't I'll re-export and upload an updated pack :)

EDIT: Sorry for the late reply as well!

**Comment by shrunbr** [comment]
Closing issue due to no reply.
